### ISSUE TITLE
Submodules not initialized when using repo according to README.md

### ISSUE THREAD

**Issue by Asd2gogo** [Autonomous-Racing-Labs/f1tenth_racecar_ws#1]
Git submodules have to be initialized in the repo after cloning.
Otherwise `git submodule update` does not fetch the resources.

`git submodule init` required before `update`

or use
`git submodule update --init --remote --merge`

according to [docs](https://git-scm.com/docs/git-submodule/2.6.7#Documentation/git-submodule.txt-init)

**Comment by wette** [comment]
fixed with https://github.com/Autonomous-Racing-Labs/f1tenth_racecar_ws/commit/ce8bf294cc758ceb30770162cd7734a43cad742d
